[workspace]
members = [
    "crates/around-core",
    "crates/around-engine",
    "crates/around-cli",
    "crates/around-codec-wav",
    "crates/around-codec-test-pcm",
    "crates/around-source-file",
    "examples/simple_decoder",
]
resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2021"
authors = ["vcup"]
repository = "https://github.com/vcup/around"
license-file = "LICENSE"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = 3
