//! Codec trait (stabby ABI), generated CodecRegister, and safe dispatch wrapper.
//!
//! This is the ADR-0004 compliant codec system using `#[stabby::stabby]` and
//! `#[slot]` instead of hand-rolled fn-pointer vtables.
//!
//! # Architecture
//!
//! - [`Codec`] — ABI-stable trait for audio format detection and decoding.
//! - [`CodecRegister`] — generated by `#[slot]`, holds all registered codecs.
//! - [`SafeCodecRef<'reg>`] — scoped handle to a registered codec, 8 bytes, zero unsafe dispatch.
//! - [`init_codec`] — SDK init function to register the Codec slot with the Framework.
//! - [`ReadFn`], [`SeekFn`] — callback types for reader I/O during `open()`.
//! - [`StreamInfo`] — audio metadata returned by [`Codec::open`].
//!
//! # Safety preconditions
//!
//! The central safety invariant: **all streams must be stopped before removing
//! codec entries.**  The `&'static` lifetime on `SafeCodecRef` is conditional —
//! it is valid only while the register holds the entry.  See [`SafeCodecRef`]
//! for the precise safety model.
//!
//! ## C-ABI design
//!
//! stabby 72 does not support `Slice<'_, [u8]>` or `SliceMut<'_, [f32]>` as
//! trait method parameters because `[u8]`/`[f32]` are unsized (DST) types and
//! cannot satisfy the `IStable` trait bound required by stabby's `Slice` — the
//! trait requires fixed layout known at the type level.  This trait uses raw
//! pointer + length pairs instead, matching the `extern "C"` calling convention
//! exactly.  See [stabby issue #72](https://github.com/ZettaScaleLabs/stabby/issues/72).

use std::ffi::c_void;
// Import stabby's Box so the generated DynCodecRef type uses the correct Box.
// The #[slot] proc-macro generates `dynptr!(Box<dyn Codec + ...>)` which
// produces an unqualified `Box<()>` — this import makes it resolve to
// `stabby::boxed::Box` instead of `std::boxed::Box`.
use stabby::boxed::Box;

use std::sync::atomic::{AtomicU32, Ordering};
// ---------------------------------------------------------------------------
// Reader callback types
// ---------------------------------------------------------------------------

/// Read callback for codec `open()`.  Returns bytes read or negative on error.
pub type ReadFn = unsafe extern "C" fn(ctx: *mut c_void, buf: *mut u8, len: usize) -> i64;

/// Seek callback for codec `open()`.  Returns new position or negative on error.
pub type SeekFn = unsafe extern "C" fn(ctx: *mut c_void, pos: i64, whence: i32) -> i64;

// ---------------------------------------------------------------------------
// Stream metadata returned by open()
// ---------------------------------------------------------------------------

/// Audio stream metadata returned by [`Codec::open`] via output parameter.
///
/// Per ADR-0004 §4.3, audio metadata is read from the container format during
/// `open()` and returned to the engine — it is not part of the Codec trait.
/// The engine uses this to configure the output pipeline.
#[repr(C)]
#[derive(Debug, Clone, Copy, Default)]
pub struct StreamInfo {
  /// Sample rate in Hz (e.g. 44100, 48000).
  pub sample_rate: u32,
  /// Number of channels (1 = mono, 2 = stereo, …).
  pub channels: u8,
  /// Total frame count, or 0 if unknown / unbounded (streaming source).
  pub total_frames: u64,
}

// ---------------------------------------------------------------------------
// ABI-stable Codec trait
// ---------------------------------------------------------------------------

/// ABI-stable codec trait for audio format detection and decoding.
///
/// Codec implementations are stateless: all per-stream state lives in the
/// opaque `stream: *mut c_void` returned from `open()`.  The engine calls
/// `probe()` to select a codec, then `open()` -> `read()` -> `drop()`.
// SAFETY: This trait's methods take raw pointers because they are ABI-stable
// extern "C" functions crossing the .so boundary.  The safety contract is at
// the FFI level: callers must pass valid pointers, and implementors must
// validate them.  Clippy's not_unsafe_ptr_arg_deref is suppressed because
// Rust's `unsafe` keyword cannot be applied to extern "C" trait method
// declarations without breaking stabby's vtable generation.
//
// The `prefix` argument sets NAME to "around_audio_sdk::Codec" — the honest
// home for the Codec trait after extraction from around-core.  Existing .so
// codec files must be recompiled with the new create symbol
// (around_audio_sdk_codec_codec_create).
#[stabby::stabby]
#[around_extensions_macros::slot(prefix = "around_audio_sdk::Codec")]
pub trait Codec {
  /// Probe a file header and filename, returning confidence 0–100.
  ///
  /// `header` points to `header_len` bytes of the file beginning (typically
  /// the first 8–16 kiB).  `filename` points to `filename_len` bytes of the
  /// file name (extension heuristic).
  ///
  /// Returns 0 = "not this format" (skip this codec), 100 = certain match.
  /// The engine probes all registered codecs and selects the highest
  /// confidence result.
  extern "C" fn probe(
    &self,
    header: *const u8,
    header_len: usize,
    filename: *const u8,
    filename_len: usize,
  ) -> u8;

  /// Return the codec name as a null-terminated C string.
  ///
  /// The returned pointer must be valid for the lifetime of the codec
  /// (typically a `&'static str` cast to `*const u8`).  The engine reads
  /// the string for logging and display purposes only; it never dereferences
  /// the pointer after the codec is unloaded.
  extern "C" fn name(&self) -> *const u8;

  /// Open a stream for decoding.
  ///
  /// `reader_ctx` + `reader_read` + `reader_seek` provide transient I/O
  /// callbacks valid only during this call.  All required metadata (header
  /// parsing, data offset discovery) must be consumed before returning.
  ///
  /// On success:
  /// - `out_stream` receives the opaque per-stream state pointer allocated by
  ///   the codec (e.g. a heap-allocated struct containing decode buffers).
  ///   The engine passes this pointer to subsequent `read()`/`seek()`/`drop()`.
  /// - `out_info` receives the audio stream metadata (sample rate, channels,
  ///   frame count) per ADR-0004 §4.3 — audio metadata is consumed from the
  ///   container during `open()`, not exposed as trait methods.
  /// - Returns 0.
  ///
  /// Returns a negative error code on failure; `out_stream` and `out_info`
  /// are left uninitialised.
  extern "C" fn open(
    &self,
    reader_ctx: *mut c_void,
    reader_read: ReadFn,
    reader_seek: SeekFn,
    out_stream: *mut *mut c_void,
    out_info: *mut StreamInfo,
  ) -> i32;

  /// Decode interleaved f32 PCM samples into `buf`.
  ///
  /// `buf` points to `buf_len` f32 elements.  Samples are always returned
  /// interleaved (L,R,L,R,... for stereo).
  ///
  /// Returns the number of decoded **samples** (not bytes), or a negative
  /// error code.  Returns 0 at end of stream (EOF).
  extern "C" fn read(&self, stream: *mut c_void, buf: *mut f32, buf_len: usize) -> i32;

  /// Seek to an absolute frame position.
  ///
  /// `frame` is the 0-based frame index (one sample per channel = one frame).
  /// The caller is responsible for converting from other time units.
  ///
  /// Returns the new position in frames, or negative on error.
  extern "C" fn seek(&self, stream: *mut c_void, frame: u64) -> i64;

  /// Drop per-stream state allocated by `open()`.
  ///
  /// Must free all resources associated with `stream` (buffers, file handles,
  /// etc.).
  extern "C" fn drop(&self, stream: *mut c_void);
}
// ---------------------------------------------------------------------------
// SafeCodecRef — scoped dispatch through stored &'reg DynCodecRef
// ---------------------------------------------------------------------------

///
/// The `'reg` lifetime ties this handle to the [`CodecRegister`] borrow that
/// produced it.  Iteration handles (`entries()` / `for_each_codec()`) carry
/// this lifetime and **cannot outlive** the register borrow — the compiler
/// enforces this.
///
/// For stream-duration storage, use [`SafeCodecRef::from_static`] (truly
/// `'static` built-in codecs) or [`SafeCodecRef::from_owned`] (intentionally
/// leaked codecs).  Plugin codecs used across stream duration require an
/// explicit `unsafe { assume_static() }` call — see the safety model below.
///
/// # Storage strategy
///
/// Holds a single `&'reg DynCodecRef` pointer — the heap-allocated fat
/// pointer already stored in the [`CodecRegister`].  This is **8 bytes** (one
/// pointer), half the size of the old [`CodecHandle`] which stored separate
/// `vtable` and `codec_data` pointers and reconstructed the fat pointer on
/// every method call.
///
/// # Dispatch mechanism
///
/// Every method delegates directly to the [`CodecDyn`] trait implementation on
/// `DynCodecRef`, which stabby generates from the [`Codec`] trait declaration.
/// Each call performs exactly one indirect jump — the same cost as the old
/// hand-rolled vtable offset dispatch, but **the offset is always correct**
/// because it is computed by stabby's proc-macro from the trait definition,
/// not hardcoded as `vtable.add(N)` magic numbers.
///
/// # Safety model
///
/// ## Methods are safe to call (not `unsafe fn`)
///
/// The [`CodecDyn`] trait methods are declared as safe `extern "C" fn` — they
/// are NOT `unsafe fn`.  They happen to accept raw pointer arguments (`stream:
/// *mut c_void`, `buf: *mut f32`, etc.), but accepting raw pointers is safe in
/// Rust; only dereferencing them is unsafe.  The safety invariant for these
/// methods is: *"the caller guarantees the stream pointer is valid for the
/// codec instance."*  This is enforced by **documentation and convention**
/// rather than the `unsafe` keyword on the method declaration.
///
/// ## The `&'reg` lifetime is conditional
///
/// `SafeCodecRef<'reg>` stores `&'reg DynCodecRef`.  This lifetime asserts
/// that the referenced `DynCodecRef` is valid for `'reg`.  For iteration
/// handles, `'reg` is tied to the register borrow — the compiler prevents
/// stashing past the borrow.  For storage handles (via `assume_static()` or
/// `from_static`/`from_owned`), the `'static` lifetime is sound only if the
/// entry is never removed while any `SafeCodecRef` pointing to it exists.
///
/// This invariant is maintained by the following conventions:
///
/// 1. **Plugin codecs:** The [`CodecRegister`] owns the `DynCodecRef`
///    allocation.  Entries are removed by `CodecRegister::remove_by_meta`,
///    which frees the entry immediately — it does **not** wait for streams.
///    Therefore, the caller must ensure **no active streams** reference the
///    entry before calling `remove_by_meta`.  In practice, this means calling
///    [`Engine::shutdown()`] (or draining all streams) before calling
///    [`Framework::unload`].
///
/// 2. **Built-in / `from_owned` codecs:** The `DynCodecRef` allocation is
///    intentionally leaked — it lives for the process lifetime and is never
///    freed.  These entries are always safe to reference.
///
/// 3. **Stream lifecycle:** The engine creates `ActiveStream` entries that
///    hold `SafeCodecRef<'static>` values.  When a stream ends (via
///    `run_stream()` or `shutdown()`), the `SafeCodecRef` is released.  The
///    engine **must not** call `remove_by_meta` until all streams using the
///    codec have been drained.
///
/// ## Code-segment safety (`dlclose` limitation)
///
/// For plugin codecs loaded via `Framework::load`, `CodecRegister::remove_by_meta`
/// frees the heap `DynCodecRef`.  Additionally, `Framework::unload()` calls
/// `dlclose` on the `.so`, unmapping its code segment.  The vtable pointer
/// inside any extant `DynCodecRef` reference points into unmapped memory —
/// immediate UB on any method call.
///
/// **No Rust type system can prevent this.**  The vtable pointer lives in the
/// `.so`'s code pages, and `dlclose` is an OS-level operation outside the
/// type system's reach.  Every approach (epochs, Arc, scoped lifetimes) ends
/// up relying on the same convention:
///
/// > **`engine.shutdown()` before `Framework::unload()`.**
///
/// Shutdown drains all streams, releasing their `SafeCodecRef` values.  Once
/// all refs are dropped, `remove_by_meta` and `dlclose` are safe.
///
/// ## What happens if the convention is violated?
///
/// If `remove_by_meta` is called while `SafeCodecRef` copies still exist:
/// - The `DynCodecRef` heap allocation is freed → the `&'reg` pointer
///   becomes dangling.
/// - Subsequent `read()`/`seek()`/`drop()` calls are **use-after-free UB**.
/// - For plugin codecs, `dlclose` also unmaps the `.so` code segment,
///   making the vtable pointer in `DynCodecRef` point into unmapped memory
///   — immediate segfault on any method call.
///
/// ## Runtime detection
///
/// > **Note:** `remove_by_meta` does NOT currently check the active-stream
/// > counter — protection relies solely on the engine lifecycle convention
/// > (shutdown all streams before unloading any extension).  The counter
/// > infrastructure exists for a future debug assertion and for manual
/// > inspection via [`debug_active_streams`].
///
/// ## Why not type-enforced safety?
///
/// Making `SafeCodecRef` non-`Copy` or adding reference counting would
/// require either:
/// - A non-trivial epoch/RCU mechanism in the register, or
/// - An `Arc` allocation on every dispatch call.
///
/// Both add cost and complexity to the 8-byte zero-overhead handle.  The
/// convention-enforced approach keeps the hot path clean while the
/// preconditions (shutdown before unload) are already satisfied by the
/// application lifecycle.  The safety-critical invariant is documented
/// and defended by a debug assertion; the production binary pays nothing.
///
/// ## Thread safety (`Send + Sync`)
///
/// `SafeCodecRef<'reg>` derives automatic `Send + Sync` because:
/// - It is `&'reg DynCodecRef` (a shared reference)
/// - `&T: Send` when `T: Sync` — satisfied because `DynCodecRef` (stabby's
///   `Dyn<Box<()>, Vt>`) uses `Box<()>` which is `Send`, and has an immutable
///   vtable that is shared across threads.
/// - `&T: Sync` when `T: Sync` — satisfied because concurrent reads through
///   the same vtable are safe; per-stream state (`stream: *mut c_void`) is
///   serialized by the engine per-stream.
///
/// No `unsafe impl Send for SafeCodecRef {}` needed.
#[derive(Clone, Copy)]
pub struct SafeCodecRef<'reg>(&'reg DynCodecRef);

impl<'reg> SafeCodecRef<'reg> {
  /// Create a `SafeCodecRef` from a `'reg` reference (scoped to register borrow).
  ///
  /// Primary constructor for iteration: the register owns the `DynCodecRef`
  /// and guarantees it lives as long as the register borrow.
  #[inline]
  pub const fn from_ref(inner: &'reg DynCodecRef) -> Self {
    Self(inner)
  }

  /// Create a `SafeCodecRef<'static>` from a `&'static DynCodecRef`.
  ///
  /// This is the escape hatch for codecs with genuinely static lifetime:
  /// built-in codecs (`from_owned`) and statically-registered codecs.
  ///
  /// # Safety
  ///
  /// The caller must ensure the referenced `DynCodecRef` remains valid
  /// for the lifetime of every `SafeCodecRef` derived from this call.
  ///
  /// This is satisfied when:
  /// - `inner` points to an entry in the [`CodecRegister`] **and**
  /// - the entry is never removed while any `SafeCodecRef` referencing
  ///   it exists (i.e., all streams are drained before unload).
  ///
  /// For `from_owned` entries (which leak), this condition holds
  /// unconditionally — the allocation is never freed.
  #[inline]
  pub const fn from_static(inner: &'static DynCodecRef) -> SafeCodecRef<'static> {
    SafeCodecRef(inner)
  }

  /// Leak an owned codec instance and return a non-owning reference.
  ///
  /// The codec will **never be freed** — the allocation lives for the
  /// remainder of the program.  This is intentional and appropriate for
  /// built-in / fallback codecs that should always be available.
  ///
  /// # Memory
  ///
  /// The leaked allocation is exactly one `DynCodecRef` struct plus the
  /// codec instance on the heap — ~64 bytes total for typical codecs.
  /// This matches the previous implicit leak semantics and is bounded
  /// (one allocation per call, typically called once per codec type).
  ///
  /// # Safety
  ///
  /// The allocation is intentionally leaked via `Box::into_raw` and never
  /// freed.  This is safe because:
  /// - The leak is a single heap allocation per codec type
  /// - The codec must outlive all streams (it is indistinguishable from
  ///   a `'static` static allocation)
  /// - The leaked memory is never touched again after construction
  ///   (the vtable is immutable; the codec implementation is shared)
  pub fn from_owned(codec: impl Codec + Send + Sync + 'static) -> SafeCodecRef<'static> {
    let bx = stabby::boxed::Box::new(codec);
    let dyn_ref: DynCodecRef = DynCodecRef::from(bx);
    // Intentionally leak the heap allocation — it lives for the process
    // lifetime, matching the semantics of a statically-registered codec.
    // `std::boxed::Box::into_raw` yields ownership; we convert the pointer
    // to a shared reference and never free it.
    let leaked: &'static DynCodecRef = {
      let bx = std::boxed::Box::new(dyn_ref);
      let ptr = std::boxed::Box::into_raw(bx);
      unsafe { &*ptr }
    };
    SafeCodecRef(leaked)
  }

  /// Escape hatch: extend reference to `'static`.
  ///
  /// This is NOT a type-level soundness hole because the caller must
  /// uphold the `'static` precondition.  It exists for the engine to
  /// convert a scoped iteration reference into a stored reference when
  /// external invariants guarantee the entry won't be removed.
  ///
  /// # Safety
  ///
  /// The caller must ensure the underlying `DynCodecRef` will outlive all
  /// uses of the returned `SafeCodecRef<'static>`:
  /// - The codec entry must NOT be removed from the register while any
  ///   stored reference exists
  /// - For built-in codecs (`from_owned`), this is automatically satisfied
  /// - For plugin codecs, this requires the engine to guarantee no
  ///   `Framework::unload()` call while streams are active
  #[inline]
  pub unsafe fn assume_static(self) -> SafeCodecRef<'static> {
    SafeCodecRef(std::mem::transmute::<&'reg DynCodecRef, &'static DynCodecRef>(self.0))
  }

  // -----------------------------------------------------------------------
  // Dispatch methods — all safe, all delegate to CodecDyn
  // -----------------------------------------------------------------------

  /// Decode interleaved `f32` PCM samples into `buf`.
  ///
  /// `stream` is the per-stream state pointer returned by [`Codec::open`].
  /// `buf` must point to `buf_len` writable `f32` elements.
  ///
  /// Returns the number of decoded samples (not bytes), 0 at EOF, or a
  /// negative error code.
  #[inline(always)]
  pub fn read(&self, stream: *mut c_void, buf: *mut f32, buf_len: usize) -> i32 {
    self.0.read(stream, buf, buf_len)
  }

  /// Seek to an absolute frame position.
  ///
  /// `frame` is the 0-based frame index (one sample per channel = one
  /// frame).  Returns the new position in frames, or a negative error code.
  #[inline(always)]
  pub fn seek(&self, stream: *mut c_void, frame: u64) -> i64 {
    self.0.seek(stream, frame)
  }

  /// Drop per-stream state allocated by [`Codec::open`].
  ///
  /// Must be called exactly once per stream, after all `read`/`seek`
  /// calls.  The engine calls this when the stream is closed.
  ///
  /// Named `drop` (matching the `Codec::drop` method) — this is NOT
  /// `Drop::drop`, so no conflict.
  ///
  /// Panics if `stream` is null (catches use-after-drop early).
  #[inline(always)]
  pub fn drop(&self, stream: *mut c_void) {
    assert!(
      !stream.is_null(),
      "SafeCodecRef::drop: stream is null (use-after-drop?)"
    );
    self.0.drop(stream)
  }

  /// Probe a file header for format detection.
  ///
  /// Returns confidence 0–100.  The engine probes all registered codecs
  /// and selects the highest confidence result.
  #[inline(always)]
  pub fn probe(
    &self,
    header: *const u8,
    header_len: usize,
    filename: *const u8,
    filename_len: usize,
  ) -> u8 {
    self.0.probe(header, header_len, filename, filename_len)
  }

  /// Return the codec name as a null-terminated C string.
  ///
  /// The pointer is valid for the codec's lifetime (program lifetime for
  /// built-in codecs; as long as the register entry exists for plugins).
  /// Reading the C string at this pointer is `unsafe` — callers must
  /// dereference it through [`CStr::from_ptr`].
  #[inline(always)]
  pub fn name(&self) -> *const u8 {
    self.0.name()
  }

  /// Open a stream for decoding.
  ///
  /// `reader_ctx`, `reader_read`, `reader_seek` provide transient I/O
  /// callbacks valid only during this call.
  #[inline(always)]
  pub fn open(
    &self,
    reader_ctx: *mut c_void,
    reader_read: ReadFn,
    reader_seek: SeekFn,
    out_stream: *mut *mut c_void,
    out_info: *mut StreamInfo,
  ) -> i32 {
    self
      .0
      .open(reader_ctx, reader_read, reader_seek, out_stream, out_info)
  }
}

// ---------------------------------------------------------------------------
// Safe iteration — CodecRegister::entries() and for_each_codec()
// ---------------------------------------------------------------------------

impl CodecRegister {
  /// Return scoped references to all registered codecs.
  ///
  /// The returned `SafeCodecRef<'a>` values are valid only for `'a`,
  /// the borrow duration of `self`.  The compiler enforces that they
  /// cannot outlive the register lock.
  ///
  /// # Dangling reference warning
  ///
  /// The references become **dangling** if [`remove_by_meta`](Self::remove_by_meta)
  /// is called on the register after this method returns, even within the
  /// borrow — the compiler prevents use after the borrow ends but does not
  /// prevent mutation while the borrow is active.
  ///
  /// The caller **must** ensure that no `remove_by_meta` call can occur
  /// while any `SafeCodecRef` from this `Vec` is still live.  In practice:
  /// - The engine calls `entries()` only during initialization, before
  ///   any stream is created, and discards the result.
  /// - If you hold the result across an unload boundary, you must drain
  ///   all references first.
  ///
  /// ## Prefer `for_each_codec`
  ///
  /// Unless you need random access or multiple iterations, use
  /// [`for_each_codec`](Self::for_each_codec) instead — it avoids the
  /// allocation and the lifetime burden of a persistent `Vec`.
  pub fn entries<'a>(&'a self) -> Vec<SafeCodecRef<'a>> {
    let mut result = Vec::new();
    self.for_each_entry(|_vtable_ptr, entry_ptr| {
      // SAFETY: entry_ptr points to a heap-allocated DynCodecRef
      // owned by this CodecRegister.  The 'a lifetime on the
      // returned SafeCodecRef ties it to the register borrow,
      // not to the lock guard.
      let dyn_ref: &'a DynCodecRef = unsafe { &*(entry_ptr as *const DynCodecRef) };
      result.push(SafeCodecRef::from_ref(dyn_ref));
    });
    result
  }

  /// Invoke `f` for each registered codec with a scoped reference.
  ///
  /// Zero-allocation alternative to [`entries()`](Self::entries).
  /// The `SafeCodecRef<'a>` passed to `f` is valid only within this
  /// call — the `'a` lifetime prevents the callback from stashing it.
  ///
  /// # Safety: callback lifetime
  ///
  /// The `SafeCodecRef<'a>` passed to `f` is valid **only during the call**.
  /// The callback **must not** store the `SafeCodecRef` past the return
  /// of `f` — the lifetime `'a` is tied to the register borrow and
  /// the compiler will prevent escape attempts.
  ///
  /// The engine's probe loop uses this API safely because it runs at
  /// stream setup time, before any concurrent `remove_by_meta` call.
  /// If the callback must retain a reference past the loop, it must
  /// use the explicit `unsafe { codec.assume_static() }` escape hatch.
  pub fn for_each_codec<'a, F: FnMut(SafeCodecRef<'a>)>(&'a self, mut f: F) {
    self.for_each_entry(|_vtable_ptr, entry_ptr| {
      // SAFETY: entry_ptr points to a heap-allocated DynCodecRef
      // owned by this CodecRegister.  The 'a lifetime ties
      // the SafeCodecRef to the &'a self borrow, preventing use
      // after the borrow ends.
      let dyn_ref: &'a DynCodecRef = unsafe { &*(entry_ptr as *const DynCodecRef) };
      f(SafeCodecRef::from_ref(dyn_ref));
    });
  }
}

// ---------------------------------------------------------------------------
// Active stream counter (debug assertion support)
// ---------------------------------------------------------------------------

/// Count of active streams, tracked for debug assertions.
///
/// The engine calls `debug_track_stream(true)` when a stream is created
/// and `debug_track_stream(false)` after a stream's codec resources are
/// released.
///
/// This counter is **only** used in `debug_assert!` calls.  Release builds
/// never access it.
static ACTIVE_STREAMS: AtomicU32 = AtomicU32::new(0);

/// Track stream lifecycle for debug assertions.
///
/// - `is_start = true`: a stream was created.
/// - `is_start = false`: a stream was fully torn down.
///
/// The engine must ensure balanced calls: every `true` must have a matching
/// `false` before a codec entry is removed.
#[inline]
pub fn debug_track_stream(is_start: bool) {
  if is_start {
    ACTIVE_STREAMS.fetch_add(1, Ordering::Relaxed);
  } else {
    ACTIVE_STREAMS.fetch_sub(1, Ordering::Relaxed);
  }
}

/// Returns the current active stream count (for debug assertions).
#[inline]
pub fn debug_active_streams() -> u32 {
  ACTIVE_STREAMS.load(Ordering::Relaxed)
}

// ---------------------------------------------------------------------------
// SDK init function
// ---------------------------------------------------------------------------

/// Initialize the Codec slot and register it with the framework.
///
/// Called once at engine startup.  Returns a reference to the global
/// [`CodecRegister`] — codec entries loaded via [`Framework::load`]
/// are pushed into this register automatically.
pub fn init_codec() -> &'static CodecRegister {
  use std::sync::LazyLock;
  static REG: LazyLock<CodecRegister> = LazyLock::new(CodecRegister::new);
  let reg: &CodecRegister = &REG;
  // SAFETY:
  // - `reg` points into static `LazyLock` storage with a stable address for
  //   the program's lifetime.
  // - The Framework stores `reg_ptr` as `*mut ()` but never writes through it;
  //   it only passes it back to `push_raw()` / `remove_by_meta()` which cast it
  //   back to `*const CodecRegister` before reading.
  // - The `*const T` -> `*mut T` cast is required by the Framework API signature.
  let reg_ptr: *const CodecRegister = reg;
  around_extensions::Framework::instance().attach_register(
    NAME,
    &REGISTER_VTABLE,
    reg_ptr as *mut (),
  );
  reg
}
