//! Filter trait (stabby ABI), generated FilterRegister, and helpers.
//!
//! This is the ADR-0006 compliant filter system using `#[stabby::stabby]` and
//! `#[slot]`, modeled on the Codec pattern in [`crate::codec`].
//!
//! # Architecture
//!
//! - [`Filter`] — ABI-stable trait for audio processing.
//! - [`FilterRegister`] — generated by `#[slot]`, holds all registered filters.
//! - [`AudioBufferC`] — C-compatible audio buffer for filter processing.
//! - [`init_filter`] — SDK init function to register the Filter slot with the Framework.
//!
//! # Safety preconditions
//!
//! See the safety model in [`crate::codec::SafeCodecRef`] — the same invariants apply.
//! Filter entries must not be removed while any stream holds a reference to them.
//!
//! ## C-ABI design
//!
//! Filter methods use `AudioBufferC` (a `#[repr(C)]` struct with raw pointer + length)
//! instead of `&mut [f32]` because stabby cannot represent `&mut [f32]` across ABI
//! boundaries — `[f32]` is unsized and cannot satisfy `IStable`.  See
//! [stabby issue #72](https://github.com/ZettaScaleLabs/stabby/issues/72).

// Import stabby's Box so the generated DynFilterRef uses the correct Box.
// The #[slot] proc-macro generates `dynptr!(Box<dyn Filter + ...>)` which
// produces an unqualified `Box<()>` — this import makes it resolve to
// `stabby::boxed::Box` instead of `std::boxed::Box`.
use stabby::boxed::Box;

// ---------------------------------------------------------------------------
// AudioBufferC — C-compatible audio buffer
// ---------------------------------------------------------------------------

/// C-compatible audio buffer for filter processing.
///
/// Wraps a pointer to interleaved f32 PCM data with length and channel metadata.
/// This is the ABI-stable equivalent of `(&mut [f32], channels)`.
///
/// # Safety
///
/// - `data` must point to at least `len` valid, initialized `f32` values
///   (aligned to `align_of::<f32>()`).
/// - The caller is responsible for ensuring the pointed-to memory is valid
///   for reads and writes for the duration of a [`Filter::process`] call.
/// - `channels` must be 1..=32 (values outside this range are undefined).
#[repr(C)]
#[derive(Debug, Clone)]
pub struct AudioBufferC {
  /// Pointer to interleaved f32 PCM data.
  pub data: *mut f32,
  /// Number of interleaved samples (not bytes) in `data`.
  pub len: usize,
  /// Number of audio channels (1 = mono, 2 = stereo, …).
  pub channels: u8,
}

// ---------------------------------------------------------------------------
// ABI-stable Filter trait
// ---------------------------------------------------------------------------

/// ABI-stable filter trait for audio processing.
///
/// Filters are stateless in their configuration but may hold per-stream state.
/// `process()` receives interleaved f32 PCM via [`AudioBufferC`] and modifies
/// it in-place.
///
/// # Safety
///
/// This trait's methods are ABI-stable `extern "C"` functions crossing the
/// `.so` boundary.  The safety contract is at the FFI level: callers must
/// pass a valid [`AudioBufferC`] (see its safety docs), and implementors
/// must validate data pointer ranges before dereferencing.
// SAFETY: process() receives a safe `&mut AudioBufferC` reference — unsafe
// only arises inside implementations when dereferencing the raw pointer
// stored in AudioBufferC.data.  This is inherent to ABI-stable traits with
// extern "C" methods; the `unsafe` keyword cannot be applied to extern "C"
// trait method declarations without breaking stabby's vtable generation.
#[stabby::stabby]
#[around_extensions_macros::slot]
pub trait Filter: Send + Sync {
  /// Return the human-readable filter name.
  extern "C" fn name(&self) -> *const u8;

  /// Process audio samples in-place.
  ///
  /// `buf` contains interleaved f32 PCM.  The filter reads from `buf.data`
  /// and writes back to `buf.data`.  Returns the number of samples produced
  /// (may differ from input after resampling — `buf.len` is NOT automatically
  /// updated; the caller should use the return value).
  ///
  /// The returned value is guaranteed to be ≤ the original `buf.len`.
  extern "C" fn process(&mut self, buf: &mut AudioBufferC) -> u32;

  /// Reset any per-stream state (accumulators, history buffers, etc.).
  ///
  /// After calling `reset()`, the filter should behave as if newly created.
  extern "C" fn reset(&mut self);
}

// ---------------------------------------------------------------------------
// Helper: convert a concrete Filter into an owned DynFilterRef
// ---------------------------------------------------------------------------

/// Convert a concrete [`Filter`] implementation into an owned [`DynFilterRef`].
///
/// The returned fat pointer owns the filter on the heap and will free it on
/// drop via stabby's allocator.  This is the primary way to construct a
/// [`DynFilterRef`] for use in a [`FilterChain`](crate::FilterChain) from a
/// built-in (non-plugin) filter.
///
/// For plugin filters loaded via [`Framework::load`](crate::Framework),
/// entries are pushed directly into the [`FilterRegister`] — this helper
/// is not needed.
pub fn make_dyn_filter(filter: impl Filter + 'static) -> DynFilterRef {
  let bx = stabby::boxed::Box::new(filter);
  DynFilterRef::from(bx)
}

// ---------------------------------------------------------------------------
// SDK init function
// ---------------------------------------------------------------------------

/// Initialize the Filter slot and register it with the framework.
///
/// Called once at engine startup.  Returns a reference to the global
/// [`FilterRegister`] — filter entries loaded via [`Framework::load`]
/// are pushed into this register automatically.
pub fn init_filter() -> &'static FilterRegister {
  use std::sync::LazyLock;
  static REG: LazyLock<FilterRegister> = LazyLock::new(FilterRegister::new);
  let reg: &FilterRegister = &REG;
  // SAFETY:
  // - `reg` points into static `LazyLock` storage with a stable address for
  //   the program's lifetime.
  // - The Framework stores `reg_ptr` as `*mut ()` but never writes through it;
  //   it only passes it back to `push_raw()` / `remove_by_meta()` which cast it
  //   back to `*const FilterRegister` before reading.
  // - The `*const T` -> `*mut T` cast is required by the Framework API signature.
  let reg_ptr: *const FilterRegister = reg;
  around_extensions::Framework::instance().attach_register(
    NAME,
    &REGISTER_VTABLE,
    reg_ptr as *mut (),
  );
  reg
}
