[package]
name = "around-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license-file.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
around-core = { workspace = true }
around-audio-sdk = { workspace = true }
around-extensions = { workspace = true }
around-source-file = { workspace = true }
around-codec-wav = { workspace = true }
kdl = { workspace = true }
tracing = { workspace = true }
cpal = { workspace = true }
tokio = { workspace = true, features = ["net", "io-util", "rt", "rt-multi-thread", "sync", "macros", "time"] }
libloading = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
crossbeam = { workspace = true }
prost = { workspace = true, optional = true }
tokio-util = { workspace = true }
parking_lot = { workspace = true }
ringbuf = { workspace = true }
base64 = { workspace = true }

[build-dependencies]
prost-build = { workspace = true, optional = true }

[dev-dependencies]
around-source-file = { workspace = true }
around-codec-test-pcm = { workspace = true }
around-core = { workspace = true, features = ["test-utils"] }

[features]
default = ["protobuf-ipc", "json-ipc", "async-decode"]
protobuf-ipc = ["prost", "prost-build"]
json-ipc = []
async-decode = []
