[package]
name = "around-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
around-core = { path = "../around-core" }
around-source-file = { path = "../around-source-file" }
around-codec-wav = { path = "../around-codec-wav" }
symphonia = { version = "0.5", default-features = false, features = ["wav"] }
knuffel = "3"
tracing = "0.1"
cpal = "0.15"
tokio = { version = "1", features = ["net", "io-util", "rt", "rt-multi-thread", "sync", "macros"] }
libloading = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"

[[bench]]
name = "pipeline_bench"
harness = false

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
around-source-file = { path = "../around-source-file" }
