[package]
name = "around-codec-wav"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license-file.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
around-core = { workspace = true }
symphonia = { workspace = true, features = ["wav"] }
