[package]
name = "around-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license-file.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
bitflags = "2"
serde = { workspace = true, features = ["derive"] }
