[package]
name = "around-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license-file.workspace = true
rust-version.workspace = true

[lints]
workspace = true
[dependencies]
bitflags = "2"
stabby = { workspace = true }
stabby-abi = { workspace = true, features = ["std", "test"] }
parking_lot = { workspace = true }
around-extensions = { workspace = true }
around-extensions-macros = { workspace = true }
serde = { workspace = true, features = ["derive"] }
