[package]
name = "around-extensions"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license-file.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
stabby = { workspace = true }
stabby-abi = { workspace = true, features = ["std", "test"] }
libloading = { workspace = true }
parking_lot = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
around-extensions-test-plugin = { path = "../around-extensions-test-plugin" }
libloading = { workspace = true }
tracing-subscriber = { workspace = true }
