[package]
name = "around-codec-test-pcm"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license-file.workspace = true
rust-version.workspace = true

[lints]
workspace = true
[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
around-audio-sdk = { workspace = true }
around-extensions = { workspace = true }
stabby = { workspace = true }
