[package]
name = "around-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license-file.workspace = true
rust-version.workspace = true
[lints]
workspace = true

[[bin]]
name = "around"
path = "src/main.rs"

[dependencies]
around-core = { workspace = true }
around-engine = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true, features = ["net", "io-util", "rt", "sync", "macros"] }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

around-source-file = { workspace = true }
ctrlc = { workspace = true }