//! Codec trait (stabby ABI) and generated CodecRegister.
//!
//! This is the ADR-0004 compliant codec system using `#[stabby::stabby]` and
//! `#[slot]` instead of hand-rolled fn-pointer vtables.
//!
//! # Architecture
//!
//! - [`Codec`] — ABI-stable trait for audio format detection and decoding.
//! - [`CodecRegister`] — generated by `#[slot]`, holds codec entries.
//! - [`init_codec`] — SDK init function to register the Codec slot.
//! - [`ReadFn`], [`SeekFn`] — callback types for reader I/O during `open()`.
//! - [`StreamInfo`] — audio metadata returned by [`Codec::open`].
//!
//! ## C-ABI design
//!
//! stabby 72 does not support `Slice<'_, [u8]>` or `SliceMut<'_, [f32]>` as
//! trait method parameters because `[u8]`/`[f32]` are unsized (DST) types and
//! cannot satisfy the `IStable` trait bound required by stabby's `Slice` — the
//! trait requires fixed layout known at the type level.  This trait uses raw
//! pointer + length pairs instead, matching the `extern "C"` calling convention
//! exactly.  See [stabby issue #72](https://github.com/ZettaScaleLabs/stabby/issues/72).

use std::ffi::c_void;
// Import stabby's Box so the generated DynCodecRef type uses the correct Box.
// The #[slot] proc-macro generates `dynptr!(Box<dyn Codec + ...>)` which
// produces an unqualified `Box<()>` — this import makes it resolve to
// `stabby::boxed::Box` instead of `std::boxed::Box`.
use stabby::boxed::Box;

// ---------------------------------------------------------------------------
// Reader callback types
// ---------------------------------------------------------------------------

/// Read callback for codec `open()`.  Returns bytes read or negative on error.
pub type ReadFn = unsafe extern "C" fn(ctx: *mut c_void, buf: *mut u8, len: usize) -> i64;

/// Seek callback for codec `open()`.  Returns new position or negative on error.
pub type SeekFn = unsafe extern "C" fn(ctx: *mut c_void, pos: i64, whence: i32) -> i64;

// ---------------------------------------------------------------------------
// Stream metadata returned by open()
// ---------------------------------------------------------------------------

/// Audio stream metadata returned by [`Codec::open`] via output parameter.
///
/// Per ADR-0004 §4.3, audio metadata is read from the container format during
/// `open()` and returned to the engine — it is not part of the Codec trait.
/// The engine uses this to configure the output pipeline.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct StreamInfo {
  /// Sample rate in Hz (e.g. 44100, 48000).
  pub sample_rate: u32,
  /// Number of channels (1 = mono, 2 = stereo, …).
  pub channels: u8,
  /// Total frame count, or 0 if unknown / unbounded (streaming source).
  pub total_frames: u64,
}

// ---------------------------------------------------------------------------
// ABI-stable Codec trait
// ---------------------------------------------------------------------------

/// ABI-stable codec trait for audio format detection and decoding.
///
/// Codec implementations are stateless: all per-stream state lives in the
/// opaque `stream: *mut c_void` returned from `open()`.  The engine calls
/// `probe()` to select a codec, then `open()` → `read()` → `drop()`.
// SAFETY: This trait's methods take raw pointers because they are ABI-stable
// extern "C" functions crossing the .so boundary.  The safety contract is at
// the FFI level: callers must pass valid pointers, and implementors must
// validate them.  Clippy's not_unsafe_ptr_arg_deref is suppressed because
// Rust's `unsafe` keyword cannot be applied to extern "C" trait method
// declarations without breaking stabby's vtable generation.
#[stabby::stabby]
#[around_extensions_macros::slot]
pub trait Codec {
  /// Probe a file header and filename, returning confidence 0–100.
  ///
  /// `header` points to `header_len` bytes of the file beginning (typically
  /// the first 8–16 kiB).  `filename` points to `filename_len` bytes of the
  /// file name (extension heuristic).
  ///
  /// Returns 0 = "not this format" (skip this codec), 100 = certain match.
  /// The engine probes all registered codecs and selects the highest
  /// confidence result.
  extern "C" fn probe(
    &self,
    header: *const u8,
    header_len: usize,
    filename: *const u8,
    filename_len: usize,
  ) -> u8;

  /// Return the codec name as a null-terminated C string.
  ///
  /// The returned pointer must be valid for the lifetime of the codec
  /// (typically a `&'static str` cast to `*const u8`).  The engine reads
  /// the string for logging and display purposes only; it never dereferences
  /// the pointer after the codec is unloaded.
  extern "C" fn name(&self) -> *const u8;

  /// Open a stream for decoding.
  ///
  /// `reader_ctx` + `reader_read` + `reader_seek` provide transient I/O
  /// callbacks valid only during this call.  All required metadata (header
  /// parsing, data offset discovery) must be consumed before returning.
  ///
  /// On success:
  /// - `out_stream` receives the opaque per-stream state pointer allocated by
  ///   the codec (e.g. a heap-allocated struct containing decode buffers).
  ///   The engine passes this pointer to subsequent `read()`/`seek()`/`drop()`.
  /// - `out_info` receives the audio stream metadata (sample rate, channels,
  ///   frame count) per ADR-0004 §4.3 — audio metadata is consumed from the
  ///   container during `open()`, not exposed as trait methods.
  /// - Returns 0.
  ///
  /// Returns a negative error code on failure; `out_stream` and `out_info`
  /// are left uninitialised.
  extern "C" fn open(
    &self,
    reader_ctx: *mut c_void,
    reader_read: ReadFn,
    reader_seek: SeekFn,
    out_stream: *mut *mut c_void,
    out_info: *mut StreamInfo,
  ) -> i32;

  /// Decode interleaved f32 PCM samples into `buf`.
  ///
  /// `buf` points to `buf_len` f32 elements.  Samples are always returned
  /// interleaved (L,R,L,R,… for stereo).
  ///
  /// Returns the number of decoded **samples** (not bytes), or a negative
  /// error code.  Returns 0 at end of stream (EOF).
  extern "C" fn read(&self, stream: *mut c_void, buf: *mut f32, buf_len: usize) -> i32;

  /// Seek to an absolute frame position.
  ///
  /// `frame` is the 0-based frame index (one sample per channel = one frame).
  /// The caller is responsible for converting from other time units.
  ///
  /// Returns the new position in frames, or negative on error.
  extern "C" fn seek(&self, stream: *mut c_void, frame: u64) -> i64;

  /// Drop per-stream state allocated by `open()`.
  ///
  /// Must free all resources associated with `stream` (buffers, file handles,
  /// decoder context, etc.).  The engine calls this once when the stream is
  /// closed, and will not call any other method with this `stream` pointer
  /// afterwards.
  extern "C" fn drop(&self, stream: *mut c_void);
}

// ---------------------------------------------------------------------------
// SDK init function
// ---------------------------------------------------------------------------

/// Initialize the Codec slot and register it with the framework.
///
/// Called once at engine startup.  Returns a reference to the global
/// [`CodecRegister`] — codec entries loaded via [`Framework::load`]
/// are pushed into this register automatically.
pub fn init_codec() -> &'static CodecRegister {
  use std::sync::LazyLock;
  static REG: LazyLock<CodecRegister> = LazyLock::new(CodecRegister::new);
  let reg: &CodecRegister = &REG;
  // SAFETY:
  // - `reg` points into static `LazyLock` storage with a stable address for
  //   the program's lifetime.
  // - The Framework stores `reg_ptr` as `*mut ()` but never writes through it;
  //   it only passes it back to `push_raw()` / `remove_by_meta()` which cast it
  //   back to `*const CodecRegister` before reading.
  // - The `*const T` → `*mut T` cast is required by the Framework API signature.
  let reg_ptr: *const CodecRegister = reg;
  around_extensions::Framework::instance().attach_register(
    NAME,
    &REGISTER_VTABLE,
    reg_ptr as *mut (),
  );
  reg
}
