[package]
name = "around-source-file"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license-file.workspace = true
rust-version.workspace = true

[lints]
workspace = true
[dependencies]
around-core = { workspace = true }
tokio = { workspace = true, features = ["fs", "io-util"] }
