[package]
name = "simple-decoder"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license-file.workspace = true
rust-version.workspace = true
[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
around-core = { workspace = true }
